### ISSUE TITLE
Bad Gateway error, trying to proxy mjpeg

### ISSUE THREAD

**Issue by WayneKeenan** [olt/corsa#3]
I'm try to add CORS headers to a UV4L video stream. 

Corsa is being run with:
`corsa --allow-proxy ALL --allow-origin ALL --bind 0.0.0.0:9999`

 I can get to the U4VL admin page, via the proxy ok:

```
http://raspberrypi.local:9999/proxy/http://raspberrypi.local:8080/
```

But clicking on the MJPG icon (which works when not proxied) results in this error eventually (30+ seconds) appearing In Chrome: 

```
stream/video.mjpeg:1 GET http://tiny4wd.local:9999/proxy/http://tiny4wd.local:8080/stream/video.mjpeg 502 (Bad Gateway)
```

Is this project still maintained?

**Comment by olt** [comment]
I'm unable to provide any support for it. But I can make a new release if you can provide a fix for any bug.

**Comment by WayneKeenan** [comment]
no worries, seems UV4L should be able to emit the headers after all.
